import = ["/home/p14/.config/alacritty/theme.toml"]

[font]
size = 12.0

[font.bold]
family = "IosevkaNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "IosevkaNerdFontMono"
style = "Bold Italic"

[font.italic]
family = "IosevkaNerdFontMono"
style = "Italic"

[font.normal]
family = "IosevkaNerdFontMono"
style = "Regular"

[shell]
program = "tmux"
args = ["new-session", "zsh"]

[window]
dynamic_title = true
opacity = 0.5
