[[plugins]]
repo = "Shougo/ddu.vim"
depends = "denops.vim"
hook_add = '''
  nnoremap <Space>fe <Cmd>Ddu file -ui=filer<CR>
  nnoremap <Leader>ff <Cmd>Ddu file_rec<CR>
'''
hook_source = '''
  call ddu#custom#load_config(expand('~/.vim/ddu.ts'))
'''

[[plugins]]
repo = "Shougo/ddu-commands.vim"
depends = "ddu.vim"
on_cmd = "Ddu"

[[plugins]]
repo = "Shougo/ddu-ui-ff"
on_source = "ddu.vim"
[plugins.ftplugin]
ddu-ff = '''
  setlocal cursorline
  nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space> <Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> i <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q <Cmd>call ddu#ui#do_action('quit')<CR>
'''

[[plugins]]
repo = "Shougo/ddu-ui-filer"
on_source = "ddu.vim"
[plugins.ftplugin]
ddu-filer = '''
  setlocal cursorline
  nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space> <Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>
  nnoremap <buffer> o <Cmd>call ddu#ui#do_action('expandItem', {'mode': 'toggle'})<CR>
  nnoremap <buffer><silent> q <Cmd>call ddu#ui#do_action('quit')<CR>
'''

[[plugins]]
repo = "Shougo/ddu-source-file"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-source-file_rec"
on_source = "ddu.vim"

[[plugins]]
repo = "kyoh86/ddu-filter-converter_hl_dir"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-filter-matcher_substring"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-filter-sorter_alpha"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-kind-file"
on_source = "ddu.vim"

[[plugins]]
repo = "Shougo/ddu-column-filename"
on_source = "ddu.vim"
