vim9script

import "~/.vim/abbreviations.vim"

import "~/.vim/autocmds.vim"

import "~/.vim/keymaps.vim"

import "~/.vim/options.vim"

import "~/.vim/plugins.vim"

abbreviations.Setup()

autocmds.Setup()

keymaps.Setup()

options.Setup()

plugins.Setup()
