vim9script

# Disable unneeded plugins
g:loaded_netrwPlugin = 1
g:loaded_logiPat = 1
g:loaded_matchparen = 1
g:loaded_gzip = 1
g:loaded_zipPlugin = 1
g:loaded_vimballPlugin = 1
g:loaded_tarPlugin = 1
g:loaded_2html_plugin = 1
g:loaded_getscriptPlugin = 1
g:loaded_manpager_plugin = 1
g:loaded_rrhelper = 1

g:mapleader = " "

const vim_config_home = expand("~/.vim")
execute "source" vim_config_home .. "/autocmd.vim"
execute "source" vim_config_home .. "/dpp.vim"
execute "source" vim_config_home .. "/options.vim"
autocmd my_vimrc_autocmd VimEnter * execute "source" vim_config_home .. "/map.vim"
