vim9script

import "~/.vim/autocmds.vim"

import "~/.vim/keymaps.vim"

import "~/.vim/options.vim"

import "~/.vim/plugins.vim"

autocmds.Setup()

plugins.Setup()

augroup vimrc
  autocmd!

  autocmd VimEnter * keymaps.Setup()

  autocmd VimEnter * options.Setup()
augroup END
