# Alias
alias g="git"
alias gc="git clone"
alias gs="git status"
alias gb="git branch"
alias gct="git commit"
alias ga="git add"
alias gpom="git push origin main"
alias gact="git add . && git commit"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias zs="source ~/.zshrc"
alias c="clear"
alias rm="wrm"
alias ln="lanb"
alias sudo="sudo "
alias clang="clang -O2 -pipe -march=native -Wall -fuse-ld=mold"
alias clang++="clang++ -O2 -pipe -march=native -Wall -std=c++20 -fuse-ld=mold"
alias e="exit"
alias grep="grep --color=auto"
alias la="ls -a --color"
alias ls="ls -s -l -h --color -G"
alias md="mkdir -pv"
