# Alias
alias g="git"
alias gc="git clone"
alias gs="git status"
alias gb="git branch"
alias gct="git commit"
alias gch="git checkout"
alias ga="git add"
alias gph="git push"
alias gpl="git pull"
alias gphom="git push origin main"
alias gplom="git pull origin main"
alias gact="git add . && git commit"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias zs="source ~/.zshrc"
alias c="clear"
alias rm="wrm"
alias ln="lanb"
alias sudo="sudo "
alias gcc="gcc -O2 -pipe -march=native -Weverything -Werror"
alias g++="g++ -O2 -pipe -march=native -Weverything -Werror -std=c++20"
alias e="exit"
alias grep="grep --color=auto"
alias la="ls -a --color"
alias ls="ls -s -l -h --color -G"
alias md="mkdir -pv"
alias less="less -g -i -M -R -S -W -z-4 -x4"
